# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbs

class EventData(object):
    NONE = 0
    ProcessStart = 1
    ProcessEnd = 2
    ProcessCreate = 3
    ProcessJoin = 4
    SocketEvent = 5

