# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbs

import flatbuffers

class FSync(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsFSync(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FSync()
        x.Init(buf, n + offset)
        return x

    # FSync
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def FSyncStart(builder): builder.StartObject(0)
def FSyncEnd(builder): return builder.EndObject()
