# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbs

import flatbuffers

class ProcessEnd(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsProcessEnd(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ProcessEnd()
        x.Init(buf, n + offset)
        return x

    # ProcessEnd
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def ProcessEndStart(builder): builder.StartObject(0)
def ProcessEndEnd(builder): return builder.EndObject()
