# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbs

import flatbuffers

class ProcessJoin(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsProcessJoin(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ProcessJoin()
        x.Init(buf, n + offset)
        return x

    # ProcessJoin
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ProcessJoin
    def ChildPid(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def ProcessJoinStart(builder): builder.StartObject(1)
def ProcessJoinAddChildPid(builder, childPid): builder.PrependUint32Slot(0, childPid, 0)
def ProcessJoinEnd(builder): return builder.EndObject()
