# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbs

import flatbuffers

class ProcessCreate(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsProcessCreate(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ProcessCreate()
        x.Init(buf, n + offset)
        return x

    # ProcessCreate
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ProcessCreate
    def ChildPid(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def ProcessCreateStart(builder): builder.StartObject(1)
def ProcessCreateAddChildPid(builder, childPid): builder.PrependUint32Slot(0, childPid, 0)
def ProcessCreateEnd(builder): return builder.EndObject()
