# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbs

class SocketEventData(object):
    NONE = 0
    SocketConnect = 1
    SocketAccept = 2
    SocketSend = 3
    SocketReceive = 4

