# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbs

import flatbuffers

class SocketConnect(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsSocketConnect(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SocketConnect()
        x.Init(buf, n + offset)
        return x

    # SocketConnect
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def SocketConnectStart(builder): builder.StartObject(0)
def SocketConnectEnd(builder): return builder.EndObject()
