# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbs

import flatbuffers

class SocketAccept(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsSocketAccept(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SocketAccept()
        x.Init(buf, n + offset)
        return x

    # SocketAccept
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def SocketAcceptStart(builder): builder.StartObject(0)
def SocketAcceptEnd(builder): return builder.EndObject()
